language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
before_install:
  - chmod +x setup.sh
  - sudo ./setup.sh
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment -c pytorch -c hcc -c conda-forge python=$TRAVIS_PYTHON_VERSION numpy=1.15.3 scipy=1.1.0 cython pytorch=0.4 torchvision libsndfile=1.0.28 libsamplerate=0.1.8 libflac=1.3.1 libogg=1.3.2
  - sudo ldconfig /opt/conda/lib
  - source activate test-environment
  - python setup.py install
  - pip install coveralls
  - ls /usr/lib/x86_64-linux-gnu/libsndfile.*
script:
  nosetests  --with-coverage --cover-package=zounds
after_success:
  coveralls